x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "3500:3500"
    depends_on:
      - mongo
      - judge0
    env_file: .env
  
  submission-webhook:
    build:
      context: .
      target: submission-webhook-production
    expose:
      - "4000"
    depends_on:
      - mongo
      - judge0
    env_file: .env

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  judge0:
    image: judge0/judge0:1.13.1
    volumes:
      - ./apps/judge0/judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./apps/judge0/judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: ./apps/judge0/judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: ./apps/judge0/judge0.conf
    <<: *default-logging
    restart: always

volumes:
  mongodb-data:
  postgres-data: